@startchen Pizzageddon_concept

entity Order {
    Id
}

entity OrderLine {
    Quantity
}

relationship Contains {

}

Order -- Contains
Contains -- OrderLine

relationship Requests {

}

entity Crust {
    Type
    Size
    Price
    LeadTime
}

entity Pizza {
    Name
    Surcharge
    LeadTimeExtension
}

entity AddOnIngredient {
    Description
    Surcharge
    LeadTimeExtension
}

entity Ingredient {
    Description
}

OrderLine -- Requests
Requests -- Crust
Requests -- Pizza
Requests -- AddOnIngredient
Requests -ToBeExcluded- Ingredient

entity Tag {
    Description
}

entity Allergen {
    Description
}

relationship CrustHas {

}

Crust -- CrustHas
CrustHas -- Tag

relationship IngredientHas {

}

Ingredient -- IngredientHas
IngredientHas -- Tag

relationship IsMadeWith {

}

Pizza -- IsMadeWith
IsMadeWith -- Ingredient


relationship CrustMayContain {

}

Crust -- CrustMayContain
CrustMayContain -- Allergen

relationship IngredientMayContain {

}

Ingredient -- IngredientMayContain
IngredientMayContain -- Allergen

Ingredient ->- AddOnIngredient


@endchen